version: "3.7"

services:
  aut_expander_mainnet:
    container_name: aut_expander_mainnet
    image: autlabs/launchpad:mainnet
    ports:
      - "5001:80"

  aut_expander_main:
    container_name: aut_expander_main
    image: autlabs/launchpad:main
    ports:
      - "5002:80"