version: "3.7"

services:
  aut_expander_playground:
    container_name: aut_expander_playground
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    networks:
      - query-server_aut-api
    ports:
      - "5002:80"

networks:
  query-server_aut-api:
    external: true
