version: "3.7"

services:
  aut_expander_prod:
    container_name: aut_expander_prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "5002:80"