version: "3.7"

services:
  aut_expander_playground:
    container_name: aut_expander_playground
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "5002:80"

networks:
  default:
    name: aut-api
    external: true
