version: '3.7'

services:

  aut-integrate-app:
    container_name: aut-integrate-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5001:80'