version: "3.7"

services:
  aut_expander_dev:
    container_name: aut_expander_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - REACT_APP_NETWORK_ENV=testnet
    ports:
      - "5002:80"