version: "3.7"

services:
  aut_expander_prod:
    container_name: aut_expander_prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "4001:80"

networks:
  default:
    name: aut-api
    external: true
