version: "3.7"

services:
  launchpad_mainnet:
    container_name: launchpad_mainnet
    image: autlabs/launchpad:mainnet
    ports:
      - "5001:80"

  launchpad_main:
    container_name: launchpad_main
    image: autlabs/launchpad:main
    ports:
      - "5001:80"