version: "3.7"

services:
  launchpad_mainnet:
    container_name: launchpad_mainnet
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_NETWORK_ENV: "mainnet"
        VITE_API_URL: "https://mainnet-api.aut.id/api"
        VITE_NODE_ENV: "production"
        VITE_DEFAULT_CHAIN_ID: "137"
    ports:
      - "5001:80"

  launchpad_main:
    container_name: launchpad_main
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_NETWORK_ENV: "testnet"
        VITE_API_URL: "https://testnet-api.aut.id/api"
        VITE_NODE_ENV: "development"
        VITE_DEFAULT_CHAIN_ID: "80002"
    ports:
      - "5001:80"
